### ISSUE TITLE
Invalid bundle after version 2.0.0

### ISSUE THREAD

**Issue by drager** [curityio/ios-idsvr-haapi-sdk-dist#2]
I upgraded IdsvrHaapiSdk from version 2.0.0 to 2.2.0 (also tried 2.1.x) but getting error after uploading the app to AppStore:

```
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html 
```

Couldn't see anything about this in your changelogs? https://curity.io/docs/haapi-ios-sdk/latest/CHANGELOG.html

**Comment by mtrojanowski** [comment]
Hey @drager,

This problem is now fixed in version 2.2.1. Should you have any more issues, please let us know.

**Comment by DanielMandea** [comment]
Unfortunately, the issue is still present I've already tried to use version `2.2.1` without success. Please check the issue opened by me https://github.com/curityio/ios-idsvr-haapi-sdk-dist/issues/3 where I explain the issue in detail and offer a few suggestions on how this should be fixed.

**Comment by mtrojanowski** [comment]
Hey @DanielMandea sorry to hear that you still have issues with publishing to the AppStore. Our mobile team will have a look at that.

I will close this issue for now and we will keep the discussion open in #3.

**Comment by drager** [comment]
> Hey @drager,
> 
> This problem is now fixed in version 2.2.1. Should you have any more issues, please let us know.

Hey @mtrojanowski,

I just tried with version 2.2.2 and it still got the same problem.
